name: Build AirVpn APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install flet telebot plyer Pillow

      - name: Build APK
        run: |
          flet build apk --yes
        env:
          # Увеличиваем таймаут для загрузки Gradle
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/apk/*.apk
